# Generated by Django 5.1.15 on 2026-01-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lti_tool', '0007_lticontext_lti1p1_id_on_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Challenge title', max_length=255)),
                ('description', models.TextField(help_text='Detailed challenge description')),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('LEGENDARY', 'Legendary')], default='COMMON', help_text='Challenge rarity/difficulty', max_length=20)),
                ('skill_tree', models.CharField(choices=[('RESEARCH', 'Research'), ('COLLABORATION', 'Collaboration'), ('CREATION', 'Creation')], help_text='Which skill tree this challenge belongs to', max_length=20)),
                ('required_tier', models.CharField(default='APPRENTICE', help_text='Minimum tier required to attempt', max_length=20)),
                ('estimated_hours', models.IntegerField(default=2, help_text='Estimated hours to complete')),
                ('xp_reward', models.IntegerField(help_text='XP awarded upon completion')),
                ('skill_points', models.IntegerField(default=10, help_text='Skill points awarded upon completion')),
                ('objectives', models.JSONField(default=list, help_text='List of challenge objectives')),
                ('success_criteria', models.JSONField(default=list, help_text='Success criteria for challenge completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this challenge is currently available')),
                ('context', models.ForeignKey(help_text='Course context this challenge belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='lti_tool.lticontext')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['rarity', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RollSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title', max_length=255)),
                ('description', models.TextField(help_text='Session description')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='UPCOMING', help_text='Current session status', max_length=20)),
                ('scheduled_start', models.DateTimeField(help_text='When session is scheduled to start')),
                ('scheduled_end', models.DateTimeField(help_text='When session is scheduled to end')),
                ('actual_start', models.DateTimeField(blank=True, help_text='When session actually started', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='When session actually ended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(help_text='Course context', on_delete=django.db.models.deletion.CASCADE, related_name='roll_sessions', to='lti_tool.lticontext')),
                ('instructor', models.ForeignKey(help_text='Instructor who created this session', on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to='lti_tool.ltiuser')),
            ],
            options={
                'verbose_name': 'Roll Session',
                'verbose_name_plural': 'Roll Sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, help_text='Total experience points')),
                ('level', models.IntegerField(default=1, help_text='Current level')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days active')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest consecutive days active')),
                ('last_activity_date', models.DateField(auto_now=True, help_text='Last activity date')),
                ('research_tier', models.CharField(default='APPRENTICE', help_text='Research skill tier (NOVICE/APPRENTICE/ADEPT/EXPERT/MASTER)', max_length=20)),
                ('research_points', models.IntegerField(default=0, help_text='Research skill points')),
                ('collaboration_tier', models.CharField(default='APPRENTICE', help_text='Collaboration skill tier', max_length=20)),
                ('collaboration_points', models.IntegerField(default=0, help_text='Collaboration skill points')),
                ('creation_tier', models.CharField(default='NOVICE', help_text='Creation skill tier', max_length=20)),
                ('creation_points', models.IntegerField(default=0, help_text='Creation skill points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(help_text='Reference to LTI Context (course)', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='lti_tool.lticontext')),
                ('lti_user', models.ForeignKey(help_text='Reference to LTI User', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='lti_tool.ltiuser')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_value', models.IntegerField(help_text='The dice roll result')),
                ('rolled_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(help_text='Challenge that was rolled for', on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='learning_tools_interoperability.challenge')),
                ('session', models.ForeignKey(help_text='Roll session this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='learning_tools_interoperability.rollsession')),
                ('profile', models.ForeignKey(help_text='Student who made the roll', on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='learning_tools_interoperability.studentprofile')),
            ],
            options={
                'verbose_name': 'Dice Roll',
                'verbose_name_plural': 'Dice Rolls',
                'ordering': ['-rolled_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Review'), ('COMPLETED', 'Completed')], default='ACTIVE', help_text='Current submission status', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When student submitted for review', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When challenge was marked complete', null=True)),
                ('submission_notes', models.TextField(blank=True, help_text="Student's notes about their submission")),
                ('submission_files', models.JSONField(default=list, help_text='List of file attachments/URLs')),
                ('reviewer_feedback', models.TextField(blank=True, help_text='Feedback from reviewer')),
                ('challenge', models.ForeignKey(help_text='Challenge being attempted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning_tools_interoperability.challenge')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Instructor who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='lti_tool.ltiuser')),
                ('profile', models.ForeignKey(help_text='Student profile', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning_tools_interoperability.studentprofile')),
            ],
            options={
                'verbose_name': 'Challenge Submission',
                'verbose_name_plural': 'Challenge Submissions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['context', 'skill_tree', 'is_active'], name='learning_to_context_e7561b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['context', 'lti_user'], name='learning_to_context_263448_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['context', 'xp'], name='learning_to_context_553e52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('lti_user', 'context')},
        ),
        migrations.AlterUniqueTogether(
            name='challengesubmission',
            unique_together={('profile', 'challenge')},
        ),
    ]
