# Generated by Django 5.1.15 on 2026-01-23 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_tools_interoperability', '0001_initial'),
        ('lti_tool', '0007_lticontext_lti1p1_id_on_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-xp'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='learning_to_context_553e52_idx',
        ),
        migrations.AlterUniqueTogether(
            name='challengesubmission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=2, help_text='Estimated hours to complete', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of challenge objectives'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='required_tier',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('APPRENTICE', 'Apprentice'), ('ADEPT', 'Adept'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], default='APPRENTICE', help_text='Minimum tier required to attempt', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='skill_points',
            field=models.PositiveIntegerField(default=10, help_text='Skill points awarded upon completion', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='success_criteria',
            field=models.JSONField(blank=True, default=list, help_text='Success criteria for challenge completion'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='xp_reward',
            field=models.PositiveIntegerField(help_text='XP awarded upon completion', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='submission_files',
            field=models.JSONField(blank=True, default=list, help_text='List of file attachments/URLs'),
        ),
        migrations.AlterField(
            model_name='diceroll',
            name='roll_value',
            field=models.PositiveSmallIntegerField(help_text='The dice roll result (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='collaboration_points',
            field=models.IntegerField(default=0, help_text='Collaboration skill points', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='collaboration_tier',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('APPRENTICE', 'Apprentice'), ('ADEPT', 'Adept'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], default='APPRENTICE', help_text='Collaboration skill tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='creation_points',
            field=models.IntegerField(default=0, help_text='Creation skill points', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='creation_tier',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('APPRENTICE', 'Apprentice'), ('ADEPT', 'Adept'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], default='NOVICE', help_text='Creation skill tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive days active', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(default=1, help_text='Current level', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Longest consecutive days active', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='research_points',
            field=models.IntegerField(default=0, help_text='Research skill points', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='research_tier',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('APPRENTICE', 'Apprentice'), ('ADEPT', 'Adept'), ('EXPERT', 'Expert'), ('MASTER', 'Master')], default='APPRENTICE', help_text='Research skill tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='xp',
            field=models.IntegerField(default=0, help_text='Total experience points', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['context', 'is_active', '-created_at'], name='learning_to_context_c25301_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['profile', 'status'], name='learning_to_profile_2a64bd_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['challenge', 'status'], name='learning_to_challen_3c8c51_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='learning_to_status_053846_idx'),
        ),
        migrations.AddIndex(
            model_name='diceroll',
            index=models.Index(fields=['session', '-rolled_at'], name='learning_to_session_8c4d82_idx'),
        ),
        migrations.AddIndex(
            model_name='diceroll',
            index=models.Index(fields=['profile', '-rolled_at'], name='learning_to_profile_446a63_idx'),
        ),
        migrations.AddIndex(
            model_name='rollsession',
            index=models.Index(fields=['context', 'status'], name='learning_to_context_1a4e53_idx'),
        ),
        migrations.AddIndex(
            model_name='rollsession',
            index=models.Index(fields=['status', 'scheduled_start'], name='learning_to_status_27cd7f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['context', '-xp'], name='learning_to_context_3deb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['last_activity_date'], name='learning_to_last_ac_500a85_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengesubmission',
            constraint=models.UniqueConstraint(fields=('profile', 'challenge'), name='unique_submission_per_profile_challenge'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('lti_user', 'context'), name='unique_profile_per_user_context'),
        ),
    ]
